### ISSUE TITLE
Exception thrown when Creating a new instance of TimeZoneDbUseCases

### ISSUE THREAD

**Issue by ldsenow** [Appease/Appease.TimeZoneDb#6]
as title. The exception is "received unexpected token type:Stringliteral when token type should have been EndLine"

Stacktrace:    
 at TimeZoneDb.TimeZoneDataSource.Iana.Etl.Extractor.Parser.Expressions.LinkExpression.TryParse(Queue`1 unProcessedTokens, Nullable`1& tzDbLink)
   at TimeZoneDb.TimeZoneDataSource.Iana.Etl.Extractor.Parser.TzDbParser.Parse(IFileInfo fileInfo, IExtractorDatabase extractorDatabase)

**Comment by ldsenow** [comment]
Had a look at the source code. I found the issue should be the ignore list in TzDbExtractor. It is very problematic. I think either white list or try-catch in the parser in case iana.org puts up some new files in the release.

**Comment by chrisdostert** [comment]
Even the official timezone db [Makefile](ftp://ftp.iana.org/tz/code/Makefile) relies on hard coded file names; afraid there's no good way around that due to lack of any kind of unique descriminator on data files vs example files etc which are included in the same distro.. 

the reasoning behind an exclusion list was it would allow immediate consumption of new data files should the IANA distrubute any.

unfortunately it seems they add new non-data files with almost every release but new data files extremely rarely (none since this library has existed). 

I've flipped the logic from an exclusion list to an inclusion list as a result of this which should solve your problem. In the event they add new data file(s) in some future version the inclusion list will just need to be updated before the new data will will be parsed.

I just pushed the fix to [NuGet](https://www.nuget.org/packages/TimeZoneDb) so you can snag it

-CD
